apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubertree.serviceAccountName" . }}
  labels:
    {{- include "kubertree.labels" . | nindent 4 }}
  {{- if .Values.oauthProxy.enabled }}
  annotations:
    serviceaccount.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "kubertree.fullname" . }}"}}
  {{- end }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
